export const ADD_WEATHER_REPORT = 'ADD_WEATHER_REPORT';
export const REMOVE_WEATHER_REPORT = 'REMOVE_WEATHER_REPORT';
export const SET_ERROR_MESSAGE = 'SET_ERROR_MESSAGE';
export const REMOVE_ERROR_MESSAGE = 'REMOVE_ERROR_MESSAGE';
